/**
 * TEMPORARY — local preview only. Returns mock admin + mock data so the
 * dashboard UI can be exercised without a real Supabase project.
 *
 * Activated by `?preview=1` query string. Real env / auth path runs
 * unchanged when the flag is absent.
 *
 * Delete after preview screenshots are taken.
 */
import type {
  Reservation,
  RestaurantSettings,
  RevenueDaily,
  RevenueMonthly,
  Payment,
  NotificationLog,
} from "@/lib/db/types";

export const PREVIEW_FLAG = "preview";

export const mockSettings: RestaurantSettings = {
  id: 1,
  total_seats: 8,
  online_seats: 8,
  seating_1_label: "17:30",
  seating_2_label: "19:30",
  seating_1_starts_at: "17:30",
  seating_2_starts_at: "19:30",
  service_minutes: 90,
  course_price_centavos: 800_000,
  deposit_pct: 50,
  refund_full_hours: 48,
  refund_partial_hours: 24,
  reminder_long_hours: 24,
  reminder_short_hours: 2,
  telegram_bot_token: "8277266976:AAEXNqk8IelMpOPu9Glebvy5jUio7awzyHk",
  telegram_chat_id: "-5035360168",
  whatsapp_from_number: "whatsapp:+14155238886",
  resend_from_email: "reservations@bar.daimasu.com.ph",
  timezone: "Asia/Manila",
  monthly_revenue_target_centavos: 25_000_000,
  display_name: "DAIMASU 大桝 BAR",
  reservations_open: true,
  updated_at: new Date().toISOString(),
};

const today = new Date();
function daysFromNow(d: number, hour = 17, min = 30): string {
  const t = new Date(today);
  t.setDate(t.getDate() + d);
  t.setHours(hour, min, 0, 0);
  return t.toISOString();
}
function dateOnly(d: number): string {
  const t = new Date(today);
  t.setDate(t.getDate() + d);
  return t.toISOString().slice(0, 10);
}

export const mockReservations: Reservation[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    service_date: dateOnly(0),
    seating: "s1",
    service_starts_at: daysFromNow(0, 17, 30),
    party_size: 4,
    guest_name: "山田 太郎",
    guest_email: "yamada@example.com",
    guest_phone: "+63 917 123 4567",
    guest_lang: "ja",
    notes: "誕生日のサプライズ・乳製品アレルギー",
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 3_200_000,
    deposit_centavos: 1_600_000,
    balance_centavos: 1_600_000,
    status: "confirmed",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(7),
    reminder_long_sent_at: null,
    reminder_short_sent_at: null,
    settled_at: null,
    settlement_method: null,
    settlement_centavos: null,
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-3),
    cancelled_at: null,
    cancelled_by: null,
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_1",
    seat_numbers: [5, 6, 7, 8],
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    service_date: dateOnly(0),
    seating: "s2",
    service_starts_at: daysFromNow(0, 19, 30),
    party_size: 2,
    guest_name: "Maria Santos",
    guest_email: "maria@example.com",
    guest_phone: "+63 918 987 6543",
    guest_lang: "en",
    notes: null,
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 1_600_000,
    deposit_centavos: 800_000,
    balance_centavos: 800_000,
    status: "confirmed",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(7),
    reminder_long_sent_at: daysFromNow(-1, 17, 30),
    reminder_short_sent_at: null,
    settled_at: null,
    settlement_method: null,
    settlement_centavos: null,
    created_at: daysFromNow(-7),
    updated_at: daysFromNow(-1),
    cancelled_at: null,
    cancelled_by: null,
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_2",
    seat_numbers: [7, 8],
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    service_date: dateOnly(2),
    seating: "s1",
    service_starts_at: daysFromNow(2, 17, 30),
    party_size: 6,
    guest_name: "Tanaka Hiroshi",
    guest_email: "tanaka@example.com",
    guest_phone: "+63 920 555 0099",
    guest_lang: "ja",
    notes: "ベジタリアン×2",
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 4_800_000,
    deposit_centavos: 2_400_000,
    balance_centavos: 2_400_000,
    status: "confirmed",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(10),
    reminder_long_sent_at: null,
    reminder_short_sent_at: null,
    settled_at: null,
    settlement_method: null,
    settlement_centavos: null,
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
    cancelled_at: null,
    cancelled_by: null,
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_3",
    seat_numbers: [3, 4, 5, 6, 7, 8],
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    service_date: dateOnly(-1),
    seating: "s1",
    service_starts_at: daysFromNow(-1, 17, 30),
    party_size: 3,
    guest_name: "Smith John",
    guest_email: "john@example.com",
    guest_phone: "+63 921 111 2222",
    guest_lang: "en",
    notes: null,
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 2_400_000,
    deposit_centavos: 1_200_000,
    balance_centavos: 1_200_000,
    status: "completed",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(0),
    reminder_long_sent_at: daysFromNow(-2),
    reminder_short_sent_at: daysFromNow(-1, 15, 30),
    settled_at: daysFromNow(-1, 21, 0),
    settlement_method: "card",
    settlement_centavos: 2_400_000,
    created_at: daysFromNow(-10),
    updated_at: daysFromNow(-1, 21, 0),
    cancelled_at: null,
    cancelled_by: null,
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_4",
    seat_numbers: [6, 7, 8],
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    service_date: dateOnly(-3),
    seating: "s2",
    service_starts_at: daysFromNow(-3, 19, 30),
    party_size: 2,
    guest_name: "佐藤 花子",
    guest_email: "sato@example.com",
    guest_phone: "+63 922 333 4444",
    guest_lang: "ja",
    notes: null,
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 1_600_000,
    deposit_centavos: 800_000,
    balance_centavos: 800_000,
    status: "no_show",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(-3),
    reminder_long_sent_at: daysFromNow(-4),
    reminder_short_sent_at: daysFromNow(-3, 17, 30),
    settled_at: null,
    settlement_method: null,
    settlement_centavos: null,
    created_at: daysFromNow(-15),
    updated_at: daysFromNow(-3, 23, 30),
    cancelled_at: daysFromNow(-3, 23, 30),
    cancelled_by: "system",
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_5",
    seat_numbers: [7, 8],
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    service_date: dateOnly(-5),
    seating: "s1",
    service_starts_at: daysFromNow(-5, 17, 30),
    party_size: 2,
    guest_name: "Garcia Ana",
    guest_email: "ana@example.com",
    guest_phone: "+63 923 555 6666",
    guest_lang: "en",
    notes: null,
    course_price_centavos: 800_000,
    deposit_pct: 50,
    total_centavos: 1_600_000,
    deposit_centavos: 800_000,
    balance_centavos: 800_000,
    status: "cancelled_full",
    cancel_token_hash: "x",
    cancel_token_expires_at: daysFromNow(-5),
    reminder_long_sent_at: null,
    reminder_short_sent_at: null,
    settled_at: null,
    settlement_method: null,
    settlement_centavos: null,
    created_at: daysFromNow(-12),
    updated_at: daysFromNow(-7),
    cancelled_at: daysFromNow(-7),
    cancelled_by: "guest",
    source: "web",
    stripe_checkout_session_id: "cs_test_demo_6",
    seat_numbers: [7, 8],
  },
];

export const mockMonthly: RevenueMonthly = {
  month_start: new Date(today.getFullYear(), today.getMonth(), 1)
    .toISOString()
    .slice(0, 10),
  covers_booked: 47,
  gross_booked_centavos: 37_600_000,
  net_completed_centavos: 18_400_000,
  no_show_deposit_kept_centavos: 1_600_000,
  no_show_lost_centavos: 800_000,
  no_show_count: 1,
  cancel_count: 3,
};

export const mockNoShow = {
  month_start: mockMonthly.month_start,
  no_show_count: 1,
  eligible_covers: 44,
  no_show_rate_pct: 2.27,
};

export const mockDaily: RevenueDaily[] = [0, 1, 2, 3, 4, 5, 6].map((i) => ({
  service_date: dateOnly(-i),
  covers_booked: [4, 6, 0, 5, 8, 7, 5][i] ?? 0,
  gross_booked_centavos:
    ([4, 6, 0, 5, 8, 7, 5][i] ?? 0) * 800_000,
  net_completed_centavos:
    i === 0 ? 0 : ([4, 6, 0, 5, 8, 7, 5][i] ?? 0) * 800_000,
  no_show_deposit_kept_centavos: i === 3 ? 800_000 : 0,
  no_show_lost_centavos: i === 3 ? 800_000 : 0,
  no_show_count: i === 3 ? 1 : 0,
  cancel_count: i === 5 ? 1 : 0,
}));

export const mockPayments: Payment[] = [
  {
    id: "p1",
    reservation_id: "11111111-1111-1111-1111-111111111111",
    kind: "deposit_capture",
    provider: "stripe",
    amount_centavos: 1_600_000,
    method: null,
    provider_ref: "pi_test_demo_1",
    idempotency_key: "stripe:event:evt_demo_1",
    notes: null,
    recorded_by: "webhook",
    created_at: daysFromNow(-3, 12, 5),
  },
];

export const mockAdmin = {
  id: "preview-admin",
  email: "owner@daimasu.com.ph",
  display_name: "DAIMASU Owner",
};

export const mockNotificationFailures: NotificationLog[] = [
  {
    id: 1,
    reservation_id: "33333333-3333-3333-3333-333333333333",
    channel: "email",
    kind: "guest_confirm",
    status: "failed",
    recipient: "tanaka@example.com",
    error_message: "Resend: 451 mailbox full",
    attempted_at: daysFromNow(-1, 12, 30),
  },
  {
    id: 2,
    reservation_id: null,
    channel: "telegram",
    kind: "admin_alert",
    status: "failed",
    recipient: "-5035360168",
    error_message: "Telegram: 401 unauthorized — bot token rotated",
    attempted_at: daysFromNow(-2, 9, 15),
  },
];
